### ISSUE TITLE
Error - Don't know how to calculate version

### ISSUE THREAD

**Issue by indusbull** [limansky/sbt-git-flow-version#3]
Hi there

When I run the plugin in my development machine, it works fine. I don't see any build issues and able to package using sbt-assembly. This is my build.sbt -

```
lazy val commonSettings = Seq(
  organization := "aa.platform",
  initialVersion := "2.4.0",
  scalaVersion := "2.12.4",
  fork in Test := true,
  parallelExecution in Test := false,
  test in Test := {},
  PB.targets in Compile := Seq(
    scalapb.gen() -> (sourceManaged in Compile).value / "protobuf"
  )
)

```
As you can see I have **initialVersion** in there. Now this same project would not build when I run in Jenkins (used for DevOps). It keeps throwing exceptions saying - " **Don't know how to calculate version**". I looked through the plugin code bug could not determine anything. Can you help pls? 

Thanks!!

```
0mCompiling 1 Scala source to /app/jenkins/workspace/workspace/AAPLATFORM.COMBINED/coderepo/project/target/scala-2.12/sbt-1.0/classes ...[0m
15:50:44 [0m[[0m[0minfo[0m] [0m[0mDone compiling.[0m
15:50:47 [0m[[0m[0minfo[0m] [0m[0mLoading settings for project global from build.sbt ...[0m
15:50:48 [0m[[0m[0minfo[0m] [0m[0mCalculating version[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0mjava.lang.RuntimeException: **Don't know how to calculate version**[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at scala.sys.package$.error(package.scala:26)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at sbtgitflowversion.GitFlowVersionPlugin$.calculateVersion(GitFlowVersionPlugin.scala:70)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at sbtgitflowversion.GitFlowVersionPlugin$.$anonfun$projectSettings$4(GitFlowVersionPlugin.scala:44)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at scala.Function1.$anonfun$compose$1(Function1.scala:44)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0m	at java.lang.Thread.run(Thread.java:745)[0m
15:50:49 [0m[[0m[31merror[0m] [0m[0mDon't know how to calculate version[0m
```

**Comment by limansky** [comment]
Hi,

  Usually it happen when you building from the detached head, or if the branch name doesn't match any rule.  Does it build on the same branch in other environment?

**Comment by indusbull** [comment]
Yes it was because of detached head. Jenkins Git plugin check outs in detached head mode. I added few additional options in configuration to fix the issue. Now it is working. Thanks for the help!!
